name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.user
        push: true
        tags: shamit10304/cicd-test2:latest  # Replace with your Docker Hub username and repository

    - name: Verify Pushed Image
      run: docker pull shamit10304/cicd-test2:latest  # Replace with your Docker Hub username and repository
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull shamit10304/cicd-test2:latest
          sudo docker stop cicd-test2 || true
          sudo docker rm cicd-test2 || true
          sudo docker run -d --name cicd-test2 -p 3001:3001 shamit10304/cicd-test2:latest